[package]
name = "haveibeenpwnd"
version = "0.1.0"
authors = ["insanitybit <insanitybit@gmail.com>"]

[dependencies]
hyper = "0.9.*"
serde = "0.8"
serde_json = "0.8"
error-chain = "0.4"
url = "1.2.0"
